- hosts: '{{ ip_addr }}'
  tasks:
    - name: Template a file to /tmp/configuracion.conf
      template:
        src: template.j2
        dest: /tmp/configuracion.conf
        mode: '0700'
        
    - name: cambio en iptables
      replace:
        path: /etc/sysconfig/iptables
        regexp: '192.168.16.1'
        replace: '192.168.100.3'
    
    - name: Reinicio iptables
      service:
        name: iptables
        state: restarted
